name: Trigger auto deployment for plan-nexus-gestao

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/plan-nexus-gestao-AutoDeployTrigger-46673c7f-bc10-4645-b0e1-0b14cb19a611.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set VITE_API_URL environment variable
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLANNEXUSGESTAO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PLANNEXUSGESTAO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PLANNEXUSGESTAO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrplannexus.azurecr.io
          registryUsername: ${{ secrets.PLANNEXUSGESTAO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PLANNEXUSGESTAO_REGISTRY_PASSWORD }}
          containerAppName: plan-nexus-gestao
          resourceGroup: plan-nexus
          imageToBuild: acrplannexus.azurecr.io/plan-nexus-gestao:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
